<style scoped>
tr:first-child,
td:first-child {
  font-weight: bold;
}

table {
  border-collapse: collapse;
}

td {
  border: 1px solid #000;
  padding: 8px;
}
@media only screen and (max-device-width: 699px) {
  table {
    font-size: 0.5em;
  }
}
</style>

<script>
export default {};
</script>



<template>
  <table>
        <tr>
            <td></td>
            <td>1,8</td>
            <td>2,0</td>
            <td>2,2</td>
            <td>2,4</td>
            <td>2,6</td>
            <td>2,8</td>
            <td>3,0</td>
            <td>3,2</td>
            <td>3,4</td>
            <td>3,6</td>
            <td>3,8</td>
            <td>4,0</td>
        </tr>
        <tr>
            <td>0°C</td>
            <td>0,1</td>
            <td>0,2</td>
            <td>0,4</td>
            <td>0,5</td>
            <td>0,6</td>
            <td>0,8</td>
            <td>0,9</td>
            <td>1,0</td>
            <td>1,1</td>
            <td>1,3</td>
            <td>1,4</td>
            <td>1,5</td>
        </tr>
        <tr>
            <td>1°C</td>
            <td>0,2</td>
            <td>0,3</td>
            <td>0,4</td>
            <td>0,6</td>
            <td>0,7</td>
            <td>0,8</td>
            <td>1,0</td>
            <td>1,1</td>
            <td>1,2</td>
            <td>1,4</td>
            <td>1,5</td>
            <td>1,6</td>
        </tr>
        <tr>
            <td>2°C</td>
            <td>0,2</td>
            <td>0,3</td>
            <td>0,5</td>
            <td>0,6</td>
            <td>0,8</td>
            <td>0,9</td>
            <td>1,0</td>
            <td>1,2</td>
            <td>1,3</td>
            <td>1,4</td>
            <td>1,6</td>
            <td>1,7</td>
        </tr>
        <tr>
            <td>3°C</td>
            <td>0,3</td>
            <td>0,4</td>
            <td>0,5</td>
            <td>0,7</td>
            <td>0,8</td>
            <td>1,0</td>
            <td>1,1</td>
            <td>1,3</td>
            <td>1,4</td>
            <td>1,5</td>
            <td>1,7</td>
            <td>1,8</td>
        </tr>
        <tr>
            <td>4°C</td>
            <td>0,3</td>
            <td>0,4</td>
            <td>0,6</td>
            <td>0,7</td>
            <td>0,9</td>
            <td>1,0</td>
            <td>1,2</td>
            <td>1,3</td>
            <td>1,5</td>
            <td>1,6</td>
            <td>1,8</td>
            <td>1,9</td>
        </tr>
        <tr>
            <td>5°C</td>
            <td>0,3</td>
            <td>0,5</td>
            <td>0,7</td>
            <td>0,8</td>
            <td>1,0</td>
            <td>1,1</td>
            <td>1,3</td>
            <td>1,4</td>
            <td>1,6</td>
            <td>1,7</td>
            <td>1,9</td>
            <td>2,0</td>
        </tr>
        <tr>
            <td>6°C</td>
            <td>0,4</td>
            <td>0,6</td>
            <td>0,7</td>
            <td>0,9</td>
            <td>1,0</td>
            <td>1,2</td>
            <td>1,3</td>
            <td>1,5</td>
            <td>1,6</td>
            <td>1,8</td>
            <td>2,0</td>
            <td>2,1</td>
        </tr>
        <tr>
            <td>7°C</td>
            <td>0,4</td>
            <td>0,6</td>
            <td>0,8</td>
            <td>0,9</td>
            <td>1,1</td>
            <td>1,3</td>
            <td>1,4</td>
            <td>1,6</td>
            <td>1,7</td>
            <td>1,9</td>
            <td>2,0</td>
            <td>2,2</td>
        </tr>
        <tr>
            <td>8°C</td>
            <td>0,5</td>
            <td>0,7</td>
            <td>0,8</td>
            <td>1,0</td>
            <td>1,2</td>
            <td>1,3</td>
            <td>1,5</td>
            <td>1,7</td>
            <td>1,8</td>
            <td>2,0</td>
            <td>2,1</td>
            <td>2,3</td>
        </tr>
        <tr>
            <td>9°C</td>
            <td>0,5</td>
            <td>0,7</td>
            <td>0,9</td>
            <td>1,1</td>
            <td>1,2</td>
            <td>1,4</td>
            <td>1,6</td>
            <td>1,7</td>
            <td>1,9</td>
            <td>2,1</td>
            <td>2,2</td>
            <td>2,4</td>
        </tr>
        <tr>
            <td>10°C</td>
            <td>0,6</td>
            <td>0,8</td>
            <td>1,0</td>
            <td>1,1</td>
            <td>1,3</td>
            <td>1,5</td>
            <td>1,6</td>
            <td>1,8</td>
            <td>2,0</td>
            <td>2,2</td>
            <td>2,3</td>
            <td>2,5</td>
        </tr>
        <tr>
            <td>11°C</td>
            <td>0,7</td>
            <td>0,8</td>
            <td>1,0</td>
            <td>1,2</td>
            <td>1,4</td>
            <td>1,5</td>
            <td>1,7</td>
            <td>1,9</td>
            <td>2,1</td>
            <td>2,2</td>
            <td>2,4</td>
            <td>2,6</td>
        </tr>
        <tr>
            <td>12°C</td>
            <td>0,7</td>
            <td>0,9</td>
            <td>1,1</td>
            <td>1,3</td>
            <td>1,4</td>
            <td>1,6</td>
            <td>1,8</td>
            <td>2,0</td>
            <td>2,2</td>
            <td>2,3</td>
            <td>2,5</td>
            <td>2,7</td>
        </tr>
        <tr>
            <td>13°C</td>
            <td>0,8</td>
            <td>0,9</td>
            <td>1,1</td>
            <td>1,3</td>
            <td>1,5</td>
            <td>1,7</td>
            <td>1,9</td>
            <td>2,1</td>
            <td>2,2</td>
            <td>2,4</td>
            <td>2,6</td>
            <td>2,8</td>
        </tr>
        <tr>
            <td>14°C</td>
            <td>0,8</td>
            <td>1,0</td>
            <td>1,2</td>
            <td>1,4</td>
            <td>1,6</td>
            <td>1,8</td>
            <td>2,0</td>
            <td>2,1</td>
            <td>2,3</td>
            <td>2,5</td>
            <td>2,7</td>
            <td>2,9</td>
        </tr>
        <tr>
            <td>15°C</td>
            <td>0,9</td>
            <td>1,1</td>
            <td>1,3</td>
            <td>1,5</td>
            <td>1,6</td>
            <td>1,8</td>
            <td>2,0</td>
            <td>2,2</td>
            <td>2,4</td>
            <td>2,6</td>
            <td>2,8</td>
            <td>3,0</td>
        </tr>
        <tr>
            <td>16°C</td>
            <td>0,9</td>
            <td>1,1</td>
            <td>1,3</td>
            <td>1,5</td>
            <td>1,7</td>
            <td>1,9</td>
            <td>2,1</td>
            <td>2,3</td>
            <td>2,5</td>
            <td>2,7</td>
            <td>2,9</td>
            <td>3,1</td>
        </tr>
        <tr>
            <td>17°C</td>
            <td>1,0</td>
            <td>1,2</td>
            <td>1,4</td>
            <td>1,6</td>
            <td>1,8</td>
            <td>2,0</td>
            <td>2,2</td>
            <td>2,4</td>
            <td>2,6</td>
            <td>2,8</td>
            <td>3,0</td>
            <td>3,2</td>
        </tr>
        <tr>
            <td>18°C</td>
            <td>1,0</td>
            <td>1,2</td>
            <td>1,5</td>
            <td>1,7</td>
            <td>1,9</td>
            <td>2,1</td>
            <td>2,3</td>
            <td>2,5</td>
            <td>2,7</td>
            <td>2,9</td>
            <td>3,1</td>
            <td>3,3</td>
        </tr>
        <tr>
            <td>19°C</td>
            <td>1,1</td>
            <td>1,3</td>
            <td>1,5</td>
            <td>1,7</td>
            <td>1,9</td>
            <td>2,2</td>
            <td>2,4</td>
            <td>2,6</td>
            <td>2,8</td>
            <td>3,0</td>
            <td>3,2</td>
            <td>3,4</td>
        </tr>
        <tr>
            <td>20°C</td>
            <td>1,1</td>
            <td>1,4</td>
            <td>1,6</td>
            <td>1,8</td>
            <td>2,0</td>
            <td>2,2</td>
            <td>2,4</td>
            <td>2,7</td>
            <td>2,9</td>
            <td>3,1</td>
            <td>3,3</td>
            <td>3,5</td>
        </tr>
        <tr>
            <td>21°C</td>
            <td>1,2</td>
            <td>1,4</td>
            <td>1,6</td>
            <td>1,9</td>
            <td>2,1</td>
            <td>2,3</td>
            <td>2,5</td>
            <td>2,7</td>
            <td>3,0</td>
            <td>3,2</td>
            <td>3,4</td>
            <td>3,6</td>
        </tr>
        <tr>
            <td>22°C</td>
            <td>1,3</td>
            <td>1,5</td>
            <td>1,7</td>
            <td>1,9</td>
            <td>2,2</td>
            <td>2,4</td>
            <td>2,6</td>
            <td>2,8</td>
            <td>3,1</td>
            <td>3,3</td>
            <td>3,5</td>
            <td>3,7</td>
        </tr>
        <tr>
            <td>23°C</td>
            <td>1,3</td>
            <td>1,6</td>
            <td>1,8</td>
            <td>2,0</td>
            <td>2,2</td>
            <td>2,5</td>
            <td>2,7</td>
            <td>2,9</td>
            <td>3,2</td>
            <td>3,4</td>
            <td>3,6</td>
            <td>3,8</td>
        </tr>
        <tr>
            <td>24°C</td>
            <td>1,4</td>
            <td>1,6</td>
            <td>1,8</td>
            <td>2,1</td>
            <td>2,3</td>
            <td>2,5</td>
            <td>2,8</td>
            <td>3,0</td>
            <td>3,2</td>
            <td>3,5</td>
            <td>3,7</td>
            <td>3,9</td>
        </tr>
        <tr>
            <td>25°C</td>
            <td>1,4</td>
            <td>1,7</td>
            <td>1,9</td>
            <td>2,2</td>
            <td>2,4</td>
            <td>2,6</td>
            <td>2,9</td>
            <td>3,1</td>
            <td>3,3</td>
            <td>3,6</td>
            <td>3,8</td>
            <td>4,0</td>
        </tr>
    </table>
</template>
